# Generated by Django 5.1.2 on 2024-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='agencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.IntegerField(),
        ),
    ]
